baseURL = 'http://f6b69a66.gh.f-g.xyz/'
languageCode = 'en-us'
title = 'gh-pages playground'

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
